unit TestCoreCriteria;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

{$I sv.inc}

uses
  TestFramework, Spring.Collections, Core.Criteria, Generics.Collections, Core.Interfaces,
  Core.Criteria.Criterion, Core.Criteria.Abstract, uModels, Core.Criteria.Restrictions
  ,Core.Session

  ;

type
  // Test methods for class TCriteria

  TestTCriteria = class(TTestCase)
  private
    FCriteria: ICriteria<TCustomer>;
    FSession: TSession;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAdd;
    procedure TestList();
  end;

implementation

uses
  Core.ConnectionFactory
  ,TestSession
  ;

procedure TestTCriteria.SetUp;
begin
  FSession := TSession.Create(TConnectionFactory.GetInstance(dtSQLite, TestDB));
  FCriteria := FSession.CreateCriteria<TCustomer>;
end;

procedure TestTCriteria.TearDown;
begin
  FCriteria := nil;
  FSession.Free;
end;

procedure TestTCriteria.TestAdd;
begin
  FCriteria.Add(TRestrictions.Eq('Name', 'Foo'))
    .Add(TRestrictions.Eq('Age', 42));
  CheckEquals(2, FCriteria.Count);
end;


procedure TestTCriteria.TestList;
var
  LCustomers: IList<TCustomer>;
begin
  LCustomers := FCriteria.Add(TRestrictions.Eq('CustName', 'Foo'))
    .Add(TRestrictions.Eq('CustAge', 42)).Add(TRestrictions.IsNull('AVATAR')).List;
  CheckTrue(Assigned(LCustomers));
  CheckEquals(0, LCustomers.Count);
  InsertCustomer(42, 'Foo');
  LCustomers := FCriteria.List;
  CheckEquals(1, LCustomers.Count);
  CheckEquals(42, LCustomers[0].Age);
  CheckEquals('Foo', LCustomers[0].Name);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCriteria.Suite);
end.

