unit ProductModel;

interface

uses
  Mapping.Attributes
  ;

type
  [Entity]
  [Table('Products')]
  TProduct = class
  private
    [Column('PRODID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'Primary Key')]
    [AutoGenerated]
    FId: Integer;
  private
    FName: string;
    FPrice: Currency;
    FQuantity: Integer;
  public
    property ID: Integer read FId;
    [Column('PRODNAME', [], 50, 0, 0, 'Product name')]
    property Name: string read FName write FName;
    [Column('PRODPRICE', [], 0, 0, 0, 'Product price')]
    property Price: Currency read FPrice write FPrice;
    [Column('PRODQUANTITY')]
    property Quantity: Integer read FQuantity write FQuantity;
  end;

implementation

end.
