unit VARTOTMASTModel;

interface

uses
  Mapping.Attributes, Core.Types, Graphics, Spring;

type
 // [Entity]
  [Table('VARTOTMAST', 'VIKARINA')]
  TVARTOTMAST = class
  private
    FVartM: Integer;
    FVartMPab: Nullable<TDateTime>; 
    FVartMVard: Nullable<String>; 
    FVartMPav: Nullable<String>; 
    FVartMKeis: Nullable<String>; 
    Fuser_id: Double; 
    FVartMPrVard: String; 
    FVartMPast: Nullable<String>; 
    FGrup_id: Nullable<Double>; 
    FVartMTip: Nullable<String>; 
    FVartMSlap: Nullable<String>; 
    FGrupe: Nullable<String>; 
    FVartMKorV: Nullable<String>; 
    FVartMTeis: Nullable<String>; 
    FVartMStat: Nullable<Double>; 
    FVartMSlPab: Nullable<TDateTime>; 
    FVartMSukDT: Nullable<TDateTime>; 
    FVartMKorD: Nullable<TDateTime>; 
    FVartMAktDT: Nullable<TDateTime>; 
    FVartMLogTip: Nullable<Integer>; 
    FVartMInval: Nullable<Integer>; 
  public
    [AutoGenerated]
    [Column('VartM', [cpPrimaryKey], -1, 14, 0, '')]
    property VartM: Integer read FVartM write FVartM;
    [Column('VartMPab', [], -1, -1, -1, '')]
    property VartMPab: Nullable<TDateTime> read FVartMPab write FVartMPab; 
    [Column('VartMVard', [], 25, -1, -1, '')]
    property VartMVard: Nullable<String> read FVartMVard write FVartMVard; 
    [Column('VartMPav', [], 25, -1, -1, '')]
    property VartMPav: Nullable<String> read FVartMPav write FVartMPav; 
    [Column('VartMKeis', [], 1, -1, -1, '')]
    property VartMKeis: Nullable<String> read FVartMKeis write FVartMKeis; 
    [Column('user_id', [], -1, 10, 0, '')]
    property user_id: Double read Fuser_id write Fuser_id; 
    [Column('VartMPrVard', [], 20, -1, -1, '')]
    property VartMPrVard: String read FVartMPrVard write FVartMPrVard; 
    [Column('VartMPast', [], 255, -1, -1, '')]
    property VartMPast: Nullable<String> read FVartMPast write FVartMPast; 
    [Column('Grup_id', [], -1, 10, 0, '')]
    property Grup_id: Nullable<Double> read FGrup_id write FGrup_id; 
    [Column('VartMTip', [], 1, -1, -1, '')]
    property VartMTip: Nullable<String> read FVartMTip write FVartMTip; 
    [Column('VartMSlap', [], 64, -1, -1, '')]
    property VartMSlap: Nullable<String> read FVartMSlap write FVartMSlap; 
    [Column('Grupe', [], 1, -1, -1, '')]
    property Grupe: Nullable<String> read FGrupe write FGrupe; 
    [Column('VartMKorV', [], 30, -1, -1, '')]
    property VartMKorV: Nullable<String> read FVartMKorV write FVartMKorV; 
    [Column('VartMTeis', [], 10, -1, -1, '')]
    property VartMTeis: Nullable<String> read FVartMTeis write FVartMTeis; 
    [Column('VartMStat', [], -1, 5, 0, '')]
    property VartMStat: Nullable<Double> read FVartMStat write FVartMStat; 
    [Column('VartMSlPab', [], -1, -1, -1, '')]
    property VartMSlPab: Nullable<TDateTime> read FVartMSlPab write FVartMSlPab; 
    [Column('VartMSukDT', [], -1, -1, -1, '')]
    property VartMSukDT: Nullable<TDateTime> read FVartMSukDT write FVartMSukDT; 
    [Column('VartMKorD', [], -1, -1, -1, '')]
    property VartMKorD: Nullable<TDateTime> read FVartMKorD write FVartMKorD;
    [Column('VartMAktDT', [], -1, -1, -1, '')]
    property VartMAktDT: Nullable<TDateTime> read FVartMAktDT write FVartMAktDT; 
    [Column('VartMLogTip', [], -1, 10, 0, '')]
    property VartMLogTip: Nullable<Integer> read FVartMLogTip write FVartMLogTip; 
    [Column('VartMInval', [], -1, 10, 0, '')]
    property VartMInval: Nullable<Integer> read FVartMInval write FVartMInval; 

  end;

implementation    
  
end.


