{***************************************************************************}
{                                                                           }
{           Spring Framework for Delphi                                     }
{                                                                           }
{           Copyright (c) 2009-2014 Spring4D Team                           }
{                                                                           }
{           http://www.spring4d.org                                         }
{                                                                           }
{***************************************************************************}
{                                                                           }
{  Licensed under the Apache License, Version 2.0 (the "License");          }
{  you may not use this file except in compliance with the License.         }
{  You may obtain a copy of the License at                                  }
{                                                                           }
{      http://www.apache.org/licenses/LICENSE-2.0                           }
{                                                                           }
{  Unless required by applicable law or agreed to in writing, software      }
{  distributed under the License is distributed on an "AS IS" BASIS,        }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. }
{  See the License for the specific language governing permissions and      }
{  limitations under the License.                                           }
{                                                                           }
{***************************************************************************}

{$I Spring.inc}

unit Spring.Persistence.Mapping.CodeGenerator.Abstract;

interface

uses
  Spring.Collections
  ,Spring.Persistence.Core.Types
  ,Spring
  ;

type
  TColumnData = class
  private
    FIsAutoGenerated: Boolean;
    FColumnName: string;
    FColumnLength: Nullable<Integer>;
    FColumnPrecision: Nullable<Integer>;
    FColumnScale: Nullable<Integer>;
    FColumnDescription: Nullable<string>;
    FIsRequired: Boolean;
    FIsUnique: Boolean;
    FDontInsert: Boolean;
    FDontUpdate: Boolean;
    FIsPrimaryKey: Boolean;
    FNotNull: Boolean;
    FIsHidden: Boolean;
    FColumnTypeName: string;
  public
    constructor Create; virtual;

    property ColumnName: string read FColumnName write FColumnName;
    property ColumnLength: Nullable<Integer> read FColumnLength write FColumnLength;
    property ColumnPrecision: Nullable<Integer> read FColumnPrecision write FColumnPrecision;
    property ColumnScale: Nullable<Integer> read FColumnScale write FColumnScale;
    property ColumnDescription: Nullable<string> read FColumnDescription write FColumnDescription;
    property ColumnTypeName: string read FColumnTypeName write FColumnTypeName;


    property IsAutogenerated: Boolean read FIsAutoGenerated write FIsAutoGenerated;
    property IsRequired: Boolean read FIsRequired write FIsRequired;
    property IsUnique: Boolean read FIsUnique write FIsUnique;
    property IsPrimaryKey: Boolean read FIsPrimaryKey write FIsPrimaryKey;
    property DontInsert: Boolean read FDontInsert write FDontInsert;
    property DontUpdate: Boolean read FDontUpdate write FDontUpdate;
    property NotNull: Boolean read FNotNull write FNotNull;
    property IsHidden: Boolean read FIsHidden write FIsHidden;
  end;

  TEntityModelData = class
  private
    FTableName: string;
    FSchemaName: string;
    FColumns: IList<TColumnData>;
  public
    constructor Create; virtual;
    destructor Destroy; override;

    function ToString: string; override;

    property TableName: string read FTableName write FTableName;
    property SchemaName: string read FSchemaName write FSchemaName;


    property Columns: IList<TColumnData> read FColumns;
  end;

  TAbstractCodeGenerator = class(TInterfacedObject)
  protected
    function GetEntityTypePrefix: string; virtual;
    function GetFielnamePrefix: string; virtual;
    function GetIndent: string; virtual;

    function DoGenerate(AEntityData: TEntityModelData): string; virtual; abstract;
  end;

implementation

uses
  SysUtils
  ;

{ TEntityData }

constructor TEntityModelData.Create;
begin
  inherited Create;
  FColumns := TCollections.CreateObjectList<TColumnData>(True);
end;

destructor TEntityModelData.Destroy;
begin
  inherited Destroy;
end;

function TEntityModelData.ToString: string;
var
  LSchema: string;
begin
  LSchema := SchemaName;

  if LSchema <> '' then
    LSchema := LSchema + '.';

  Result := Format('%0:S%1:S [%2:D]', [LSchema, TableName, Columns.Count]);
end;

{ TColumnData }

constructor TColumnData.Create;
begin
  inherited Create;
end;

{ TAbstractCodeGenerator }

function TAbstractCodeGenerator.GetEntityTypePrefix: string;
begin
  Result := 'T';
end;

function TAbstractCodeGenerator.GetFielnamePrefix: string;
begin
  Result := 'F';
end;

function TAbstractCodeGenerator.GetIndent: string;
begin
  Result := '  ';
end;

end.
